# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  displayName: 'Init terraform'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'learning'
    backendAzureRmResourceGroupName: 'rg-insight-de'
    backendAzureRmStorageAccountName: 'learning03'
    backendAzureRmContainerName: 'tfstatede'
    backendAzureRmKey: 'insight.terraform.tfstatede'

- task: TerraformTaskV2@2
  displayName: 'Validate terraform'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV2@2
  displayName: 'Plan terraform'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    publishPlanResults: 'out.plan'
    environmentServiceNameAzureRM: 'learning'

- task: TerraformTaskV2@2
  displayName: 'Apply terraform'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'learning'